#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCompiled.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.WebPages.OAuth;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/_ExternalLoginsListPartial.cshtml")]
    public partial class ExternalLoginsListPartial : System.Web.Mvc.WebViewPage<ICollection<AuthenticationClientData>>
    {
        public ExternalLoginsListPartial()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
 if (Model.Count == 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"message-info\"");

WriteLiteral(">\r\n        <p>There are no external authentication services configured. See <a");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=252166\"");

WriteLiteral(">this article</a>\r\n        for details on setting up this ASP.NET application to " +
"support logging in via external services.</p>\r\n    </div>\r\n");

            
            #line 9 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
}
else
{
    using (Html.BeginForm("ExternalLogin", "Account", new { ReturnUrl = ViewBag.ReturnUrl }))
    {
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <fieldset");

WriteLiteral(" id=\"socialLoginList\"");

WriteLiteral(">\r\n        <legend>Log in using another service</legend>\r\n        <p>\r\n");

            
            #line 18 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
        
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
         foreach (AuthenticationClientData p in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" name=\"provider\"");

WriteAttribute("value", Tuple.Create(" value=\"", 740), Tuple.Create("\"", 784)
            
            #line 20 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
, Tuple.Create(Tuple.Create("", 748), Tuple.Create<System.Object, System.Int32>(p.AuthenticationClient.ProviderName
            
            #line default
            #line hidden
, 748), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 785), Tuple.Create("\"", 833)
, Tuple.Create(Tuple.Create("", 793), Tuple.Create("Log", 793), true)
, Tuple.Create(Tuple.Create(" ", 796), Tuple.Create("in", 797), true)
, Tuple.Create(Tuple.Create(" ", 799), Tuple.Create("using", 800), true)
, Tuple.Create(Tuple.Create(" ", 805), Tuple.Create("your", 806), true)
            
            #line 20 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                        , Tuple.Create(Tuple.Create(" ", 810), Tuple.Create<System.Object, System.Int32>(p.DisplayName
            
            #line default
            #line hidden
, 811), false)
, Tuple.Create(Tuple.Create(" ", 825), Tuple.Create("account", 826), true)
);

WriteLiteral(">");

            
            #line 20 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                                                                                                                           Write(p.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 21 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        </p>\r\n    </fieldset>\r\n");

            
            #line 24 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
    }
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
