#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCompiled.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.WebPages.OAuth;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/_RemoveExternalLoginsPartial.cshtml")]
    public partial class RemoveExternalLoginsPartial : System.Web.Mvc.WebViewPage<ICollection<PreCompiled.Models.ExternalLogin>>
    {
        public RemoveExternalLoginsPartial()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
 if (Model.Count > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <h3>Registered external logins</h3>\r\n");

WriteLiteral("    <table>\r\n        <tbody>\r\n");

            
            #line 8 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
        
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
         foreach (PreCompiled.Models.ExternalLogin externalLogin in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>");

            
            #line 11 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
               Write(externalLogin.ProviderDisplayName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>\r\n");

            
            #line 13 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
                     if (ViewBag.ShowRemoveButton)
                    {
                        using (Html.BeginForm("Disassociate", "Account"))
                        {
                            
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
                       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
                                                    

            
            #line default
            #line hidden
WriteLiteral("                            <div>\r\n");

WriteLiteral("                                ");

            
            #line 19 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
                           Write(Html.Hidden("provider", externalLogin.Provider));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 20 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
                           Write(Html.Hidden("providerUserId", externalLogin.ProviderUserId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Remove\"");

WriteAttribute("title", Tuple.Create(" title=\"", 850), Tuple.Create("\"", 933)
, Tuple.Create(Tuple.Create("", 858), Tuple.Create("Remove", 858), true)
, Tuple.Create(Tuple.Create(" ", 864), Tuple.Create("this", 865), true)
            
            #line 21 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
       , Tuple.Create(Tuple.Create(" ", 869), Tuple.Create<System.Object, System.Int32>(externalLogin.ProviderDisplayName
            
            #line default
            #line hidden
, 870), false)
, Tuple.Create(Tuple.Create(" ", 904), Tuple.Create("credential", 905), true)
, Tuple.Create(Tuple.Create(" ", 915), Tuple.Create("from", 916), true)
, Tuple.Create(Tuple.Create(" ", 920), Tuple.Create("your", 921), true)
, Tuple.Create(Tuple.Create(" ", 925), Tuple.Create("account", 926), true)
);

WriteLiteral(" />\r\n                            </div>\r\n");

            
            #line 23 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
                        }
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral(" &nbsp;\r\n");

            
            #line 28 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n            </tr>\r\n");

            
            #line 31 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n");

            
            #line 34 "..\..\Views\Account\_RemoveExternalLoginsPartial.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
