#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCompiled.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.WebPages.OAuth;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/_SetPasswordPartial.cshtml")]
    public partial class SetPasswordPartial : System.Web.Mvc.WebViewPage<PreCompiled.Models.LocalPasswordModel>
    {
        public SetPasswordPartial()
        {
        }
        public override void Execute()
        {
WriteLiteral("<p>\r\n    You do not have a local password for this site. Add a local\r\n    passwor" +
"d so you can log in without an external login.\r\n</p>\r\n\r\n");

            
            #line 8 "..\..\Views\Account\_SetPasswordPartial.cshtml"
 using (Html.BeginForm("Manage", "Account")) {
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\_SetPasswordPartial.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\_SetPasswordPartial.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Account\_SetPasswordPartial.cshtml"
Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Account\_SetPasswordPartial.cshtml"
                             


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>Set Password Form</legend>\r\n        <ol>\r\n       " +
"     <li>\r\n");

WriteLiteral("                ");

            
            #line 16 "..\..\Views\Account\_SetPasswordPartial.cshtml"
           Write(Html.LabelFor(m => m.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 17 "..\..\Views\Account\_SetPasswordPartial.cshtml"
           Write(Html.PasswordFor(m => m.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li>\r\n");

WriteLiteral("                ");

            
            #line 20 "..\..\Views\Account\_SetPasswordPartial.cshtml"
           Write(Html.LabelFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 21 "..\..\Views\Account\_SetPasswordPartial.cshtml"
           Write(Html.PasswordFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n        </ol>\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Set password\"");

WriteLiteral(" />\r\n    </fieldset>\r\n");

            
            #line 26 "..\..\Views\Account\_SetPasswordPartial.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
