#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCompiled.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.WebPages.OAuth;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ExternalLoginConfirmation.cshtml")]
    public partial class ExternalLoginConfirmation : System.Web.Mvc.WebViewPage<PreCompiled.Models.RegisterExternalLoginModel>
    {
        public ExternalLoginConfirmation()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
  
    ViewBag.Title = "Register";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 7 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Associate your ");

            
            #line 8 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                  Write(ViewBag.ProviderDisplayName);

            
            #line default
            #line hidden
WriteLiteral(" account.</h2>\r\n</hgroup>\r\n\r\n");

            
            #line 11 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
 using (Html.BeginForm("ExternalLoginConfirmation", "Account", new { ReturnUrl = ViewBag.ReturnUrl })) {
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>Association Form</legend>\r\n        <p>\r\n         " +
"   You\'ve successfully authenticated with <strong>");

            
            #line 18 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                                                      Write(ViewBag.ProviderDisplayName);

            
            #line default
            #line hidden
WriteLiteral("</strong>.\r\n            Please enter a user name for this site below and click th" +
"e Confirm button to finish\r\n            logging in.\r\n        </p>\r\n        <ol>\r" +
"\n            <li");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
           Write(Html.LabelFor(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
           Write(Html.TextBoxFor(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 26 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
           Write(Html.ValidationMessageFor(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n        </ol>\r\n");

WriteLiteral("        ");

            
            #line 29 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
   Write(Html.HiddenFor(m => m.ExternalLoginData));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Register\"");

WriteLiteral(" />\r\n    </fieldset>\r\n");

            
            #line 32 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 35 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
