#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCompiled.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.WebPages.OAuth;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Contact.cshtml")]
    public partial class Contact : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Contact()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Contact.cshtml"
  
    ViewBag.Title = "Contact";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 6 "..\..\Views\Home\Contact.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>");

            
            #line 7 "..\..\Views\Home\Contact.cshtml"
   Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n</hgroup>\r\n\r\n<section");

WriteLiteral(" class=\"contact\"");

WriteLiteral(">\r\n    <header>\r\n        <h3>Phone</h3>\r\n    </header>\r\n    <p>\r\n        <span");

WriteLiteral(" class=\"label\"");

WriteLiteral(">Main:</span>\r\n        <span>425.555.0100</span>\r\n    </p>\r\n    <p>\r\n        <spa" +
"n");

WriteLiteral(" class=\"label\"");

WriteLiteral(">After Hours:</span>\r\n        <span>425.555.0199</span>\r\n    </p>\r\n</section>\r\n\r\n" +
"<section");

WriteLiteral(" class=\"contact\"");

WriteLiteral(">\r\n    <header>\r\n        <h3>Email</h3>\r\n    </header>\r\n    <p>\r\n        <span");

WriteLiteral(" class=\"label\"");

WriteLiteral(">Support:</span>\r\n        <span><a");

WriteLiteral(" href=\"mailto:Support@example.com\"");

WriteLiteral(">Support@example.com</a></span>\r\n    </p>\r\n    <p>\r\n        <span");

WriteLiteral(" class=\"label\"");

WriteLiteral(">Marketing:</span>\r\n        <span><a");

WriteLiteral(" href=\"mailto:Marketing@example.com\"");

WriteLiteral(">Marketing@example.com</a></span>\r\n    </p>\r\n    <p>\r\n        <span");

WriteLiteral(" class=\"label\"");

WriteLiteral(">General:</span>\r\n        <span><a");

WriteLiteral(" href=\"mailto:General@example.com\"");

WriteLiteral(">General@example.com</a></span>\r\n    </p>\r\n</section>\r\n\r\n<section");

WriteLiteral(" class=\"contact\"");

WriteLiteral(">\r\n    <header>\r\n        <h3>Address</h3>\r\n    </header>\r\n    <p>\r\n        One Mi" +
"crosoft Way<br />\r\n        Redmond, WA 98052-6399\r\n    </p>\r\n</section>");

        }
    }
}
#pragma warning restore 1591
